[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.testnet]
unicity_bridge = "9q5thPnZG7FKKNr61wceXdfuy2QRLYky8RTJonh2YzyB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
